# Generated by Django 4.0.1 on 2022-03-25 06:59

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_buy_created_at_remove_buy_user_buy_cost_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[shop.validators.image_resolution_check_big], verbose_name='Большое Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='cart_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[shop.validators.image_resolution_check_cart], verbose_name='Изображение для таблицы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[shop.validators.image_resolution_check_small], verbose_name='Маленькое Изображение'),
        ),
    ]
