# Generated by Django 4.0.1 on 2022-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_category_prod_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='choice',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
