# Generated by Django 4.0.1 on 2022-03-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_external_id_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
    ]
