# Generated by Django 4.0.1 on 2022-03-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
