# Generated by Django 4.0.1 on 2022-03-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_post_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.product'),
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
